# 2026-07-14 (P6): `python -m prospectra`, and the entry point PyInstaller bundles.
# Why a separate module: a frozen app needs a real script file to start from — the console-script
# shim generated by pip/uv does not exist inside the bundle.

from prospectra.cli import main

if __name__ == "__main__":
    raise SystemExit(main())
